tools:

  - name: "subtract"
    module: "tools.math_tools"
    function: "subtract"
    description: "Subtract two numbers from string 'a,b'"


  - name: "addition"
    module: "tools.math_tools"
    function: "addition"
    description: "Add two numbers from string 'a,b'"
